src/instaa/urls.py
from django.urls import path

from instaa.views import SignUpView

from instaa.views import login_user, home, logout_user, upload_photo, user_photos, my_photos, delete_photo
from django.conf import settings
from django.conf.urls.static import static
app_name = 'instaa'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('', home, name='home'),
    path('upload/', upload_photo, name='upload'),
    path('users/<slug:username>/photos/', user_photos, name='user_photos'),
    path('profile/photos/', my_photos, name='my_photos'),
    path('profile/photos/delete/<int:id>', delete_photo, name='delete_photo'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/photoupload/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('instaa.urls')),
]

src/instaa/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Photo(models.Model):
    title = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    photo = models.ImageField(blank=False,
                              upload_to='photos',
                              verbose_name="photo")

src/instaa/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView

from instaa.models import Photo


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('instaa:login')
    template_name = 'signup.html'


def login_user(request):
    if request.user.is_authenticated:
        return redirect('')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'home.html', {})
            else:
                return render(request, 'signin.html', {'error': 'Your account has been disabled'})
        else:
            return render(request, 'signin.html', {'error': 'Invalid login'})
    return render(request, 'signin.html', {})


@login_required(login_url='/login')
def logout_user(request):
    logout(request)
    return redirect('/login')


@login_required(login_url='/login')
def home(request):
    photos = Photo.objects.all()
    return render(request, 'home.html', {'photos': photos})


@login_required(login_url='/login')
def upload_photo(request):
    if request.method == 'POST':
        new_photo = Photo(title=request.POST['title'], user=request.user, photo=request.FILES['photo'])
        new_photo.save()
        return HttpResponseRedirect(reverse('instaa:home'))
    return render(request, 'upload.html', {})


@login_required(login_url='/login')
def user_photos(request, username=None):
    try:
        user = User.objects.get(username=username)
    except:
        return render(request, 'user_photos.html', {'error': "This user doesn't exists"})

    photos = user.photo_set.all()
    context = {'photos': photos, 'p_user': user}
    return render(request, 'user_photos.html', context)


@login_required(login_url='/login')
def my_photos(request):
    photos = request.user.photo_set.all()
    context = {'photos': photos, 'p_user': request.user}
    return render(request, 'my_photos.html', context)


@login_required(login_url='/login')
def delete_photo(request, id=None):
    photo = Photo.objects.get(id=id)
    photo.delete()
    return redirect('/profile/photos')

src/instaa/templates/app.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Instaa App</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Instagram</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="/upload">Upload</a></li>
                    <li><a href="{% url 'instaa:my_photos' %}">My Uploads</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"
                           aria-haspopup="true">
                            {{ request.user.username }}<span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu">
                            <li>
                                <a href="">
                                    {{ request.user.username|capfirst }}
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'instaa:logout' %}">
                                    Logout
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'instaa:login' %}">Login</a></li>
                    <li><a href="{% url 'instaa:signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div style="margin-top: 60px">
        {% if error %}
            <div class="alert alert-danger text-center">
                {{ error }}
            </div>
        {% endif %}
        {% block content %}{% endblock %}
    </div>
</div><!-- /.container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

src/instaa/templates/home.html
{% extends 'app.html' %}

{% block content %}

    <div class="row">
        {% for photo in photos %}
            <div class="col-md-4" style="margin-bottom: 10px">
                <img src="{{ photo.photo.url }}" class="img-responsive">
                <p style="margin-top: 5px"><strong>{{ photo.title }}</strong></p>
                Uploaded By - <strong><a href="
                    {% url 'instaa:user_photos' photo.user.username %}">{{ photo.user.username }}</a></strong>
            </div>
        {% endfor %}
    </div>

{% endblock %}

src/instaa/templates/my_photos.html
{% extends 'app.html' %}

{% block content %}

    <div class="row">
        {% if p_user %}
            <h3 class="text-center">Photos By {{ p_user.username }}</h3>
        {% endif %}

        {% for photo in photos %}
            <div class="col-md-4" style="margin-bottom: 10px">
                <img src="{{ photo.photo.url }}" class="img-responsive">
                <p style="margin-top: 5px"><strong>{{ photo.title }}</strong></p>
                <form action="{% url 'instaa:delete_photo' photo.id %}" method="post" style="margin-top: 15px">
                    {% csrf_token %}
                    <input type="submit" value="Delete it!" class="btn btn-danger">
                </form>
            </div>
        {% endfor %}
    </div>

{% endblock %}

src/instaa/templates/signin.html
{% extends 'app.html' %}

{% block content %}

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Login</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{% url 'instaa:login' %}">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="username" class="col-md-4 control-label">Username</label>

                            <div class="col-md-6">
                                <input id="username" type="text" class="form-control" name="username" value="" required
                                       autofocus>

                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Login
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/instaa/templates/signup.html
{% extends 'app.html' %}

{% block content %}

    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>

{% endblock %}

src/instaa/templates/upload.html
{% extends 'app.html' %}

{% block content %}

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-primary">
                <div class="panel-heading">Upload photo</div>

                <div class="panel-body">
                    <form class="form-horizontal" enctype="multipart/form-data" method="POST" action="{% url 'instaa:upload' %}">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="title" class="col-md-4 control-label">Title</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control" name="title" required
                                       autofocus>

                            </div>
                        </div>

                        <div class="form-group">
                            <label for="photo" class="col-md-4 control-label">Choose photo</label>

                            <div class="col-md-6">
                                <input id="photo" type="file" accept="image/*" class="form-control" name="photo" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Upload
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/instaa/templates/user_photos.html
{% extends 'app.html' %}

{% block content %}

    <div class="row">
        {% if p_user %}
            <h3 class="text-center">Photos By {{ p_user.username }}</h3>
        {% endif %}

        {% for photo in photos %}
            <div class="col-md-4" style="margin-bottom: 10px">
                <img src="{{ photo.photo.url }}" class="img-responsive">
                <p style="margin-top: 5px"><strong>{{ photo.title }}</strong></p>
            </div>
        {% endfor %}
    </div>

{% endblock %}